MODEL:
  VOXEL_ON: True
  MESH_ON: True
  USE_GT_DEPTH: True
  CONTRASTIVE_DEPTH_TYPE: "input_concat"
  FEATURE_FUSION_METHOD: "multihead_attention"
  CHECKPOINT: ""
  VOXEL_HEAD:
    NUM_CONV: 4
    CONV_DIM: 256
    VOXEL_SIZE: 48
    LOSS_WEIGHT: 1.0
    CUBIFY_THRESH: 0.2
    VOXEL_ONLY_ITERS: 0
    RGB_FEATURES_INPUT: True
    DEPTH_FEATURES_INPUT: False
    RGB_BACKBONE: "resnet50"
    DEPTH_BACKBONE: "vgg"
    DEPTH_FEATURES_INPUT: False
  MESH_HEAD:
    NAME: "MeshDepthHead"
    NUM_STAGES: 3
    NUM_GRAPH_CONVS: 3
    GRAPH_CONV_DIM: 128
    GRAPH_CONV_INIT: "normal"
    GT_NUM_SAMPLES: 9000
    PRED_NUM_SAMPLES: 6466
    UPSAMPLE_PRED_MESH: True
    CHAMFER_LOSS_WEIGHT: 1.0
    NORMALS_LOSS_WEIGHT: 1.6e-4
    EDGE_LOSS_WEIGHT: 0.2
    RGB_FEATURES_INPUT: True
    DEPTH_FEATURES_INPUT: True
    RGB_BACKBONE: "resnet50"
    DEPTH_BACKBONE: "vgg"
  MVSNET:
    CHECKPOINT: ""
    FEATURES_LIST: [32, 64, 128, 256]
    FREEZE: False
    RENDERED_DEPTH_WEIGHT: 0.001
    RENDERED_VS_GT_DEPTH_WEIGHT: 0.00
  MULTIHEAD_ATTENTION:
      FEATURE_DIMS: 480
      NUM_HEADS: 5
DATASETS:
  NAME: "ocrtoc"
  TYPE: "depth"
SOLVER:
  BATCH_SIZE: 1
  BATCH_SIZE_EVAL: 1
  NUM_EPOCHS: 41
  BASE_LR: 0.0001
  OPTIMIZER: "adam"
  LR_SCHEDULER_NAME: "constant"
  LOGGING_PERIOD: 5 # 0
